[package]
name = "mcfunction-debugger"
version = "0.1.0"
authors = ["Adrodoc <adrodoc55@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
walkdir = "2.3"
