[package]
name = "mcfunction-debugger"
version = "0.1.0"
authors = ["Adrodoc <adrodoc55@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
const_format = "0.2"
futures = "0.3"
log = "0.4"
multimap = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "rt-multi-thread", "macros"] }
walkdir = "2"

[dev-dependencies]
minect = { git = "ssh://git@github.com/mcfunction-debugger/minect.git" }
serial_test = "0.5"

[build-dependencies]
walkdir = "2"
